### ISSUE TITLE
重定向输出

### ISSUE THREAD

**Issue by Huaflwr** [ffffffff0x/ones#3]
建议增加-o参数，自定义输出结果的文件名。

**Comment by No-Github** [comment]
这周末会更新 go 实现的版本,届时会有自定义输出格式的功能,师傅还请耐心等待下

**Comment by No-Github** [comment]
新版本已经推上去了,重定向输出目前也支持 json 和 txt 的格式,目前查询引擎剩下 zoomeye 和 shodan 没有适配,后面等我这边空下来在更新上去, 没有其他问题,这个 issue 我就先关闭了,后面师傅有好的建议和需求也可以在 issue 提出来
