### ISSUE TITLE
hunter数量较多时查询会出错

### ISSUE THREAD

**Issue by Huaflwr** [ffffffff0x/ones#5]
如图，数量为10，结果没问题；但数量填1000时会查询出错，查询结果为空。
版本：1.0.3，系统信息：Ubuntu 20.04.1 LTS
![image](https://user-images.githubusercontent.com/57829076/180390990-c6845c91-23e1-4555-bbf7-80c908ad5c9b.png)

**Comment by No-Github** [comment]
<img width="538" alt="Snipaste_2022-08-17_19-01-01" src="https://user-images.githubusercontent.com/18167071/185110747-0b93373d-7602-4ec5-8113-d734fb3bd557.png">
page_size 参数有大小限制,之前没注意,后面更新下

**Comment by No-Github** [comment]
<img width="730" alt="Snipaste_2022-08-17_20-27-09" src="https://user-images.githubusercontent.com/18167071/185283172-75ca6081-5ee4-4a3e-b789-e8f09fb7e113.png">
<img width="497" alt="Snipaste_2022-08-17_20-27-22" src="https://user-images.githubusercontent.com/18167071/185283195-49e7b617-d28f-478d-adcc-2e4100ec116e.png">

更新了一下，现在应该可以了

**Comment by No-Github** [comment]
新版本已经推上去了,师傅可以自行下载测试一下 没有其他问题,这个 issue 我就先关闭了,后面师傅有好的建议和需求也可以在 issue 提出来
