### ISSUE TITLE
执行失败了

### ISSUE THREAD

**Issue by xsbod** [ffffffff0x/ones#6]
![图片](https://user-images.githubusercontent.com/81458807/187119563-00b81bb0-cea0-494f-844f-b268b803e64f.png)
} invalid character 'C' after object key:value pair

goroutine 1 [running]:
log.Panicln({0xc000107ce0?, 0xdc?, 0xdc?})
        /opt/hostedtoolcache/go/1.18.5/x64/src/log/log.go:399 +0x65
ones/mod.LoadConfig({0x3dd95e?, 0xede65?})
        /home/runner/work/ones/ones/mod/config.go:42 +0x196
ones/mod.Init.func1()
        /home/runner/work/ones/ones/mod/config.go:58 +0x46
sync.(*Once).doSlow(0x3dd95e?, 0x10?)
        /opt/hostedtoolcache/go/1.18.5/x64/src/sync/once.go:68 +0xc2
sync.(*Once).Do(...)
        /opt/hostedtoolcache/go/1.18.5/x64/src/sync/once.go:59
ones/mod.Init({0x3dd95e, 0x10})
        /home/runner/work/ones/ones/mod/config.go:57 +0x7a
main.main()
        /home/runner/work/ones/ones/main.go:24 +0xd0
PS C:\Users\Administrator\Desktop\pytest\ones_1.0.4>

**Comment by No-Github** [comment]
请使用新版本ones，并使用新的配置文件格式再次尝试,从图上报错看，疑似是配置文件格式错误，就是key值没有用双引号扩起来。
