### ISSUE TITLE
将查询语句放在文件内，执行报错token疑似失效

### ISSUE THREAD

**Issue by Huaflwr** [ffffffff0x/ones#7]
我编写了一个脚本来调用ones，并进行后续的结果数据处理。但是我碰到一个问题，如题，请指教。
读取文件内容来执行查询的过程类似如下：
```
vim fofa.txt
file=fofa.txt
./ones -fofa `echo "'$(<$file)'"` -num 10
```

下面是我的报错详情图：
![image](https://user-images.githubusercontent.com/57829076/194686293-1481028e-caab-4400-8a46-e12f342d52e3.png)

**Comment by No-Github** [comment]
`echo "'$(<$file)'"` 命令得到的结果前后带了一个 `'` 号,这个会导致fofa api报错
<img width="1526" alt="image" src="https://user-images.githubusercontent.com/18167071/195984154-e7dacb52-efc4-4cca-9692-861509e06a48.png">

可以用 `cat fofa.txt` 获取查询语句赋值给一个临时变量
```
querystring=`cat fofa.txt`
./ones -fofa $querystring -num 10
```

<img width="1194" alt="image" src="https://user-images.githubusercontent.com/18167071/195984205-d0113cdb-5898-45d1-9e1b-d726b2426436.png">

**Comment by Huaflwr** [comment]
好的，学习了。
