### ISSUE TITLE
执行无输出

### ISSUE THREAD

**Issue by hanxiansheng26** [ffffffff0x/ones#8]
执行无输出 
![image](https://user-images.githubusercontent.com/38833353/200173783-f7ae03b4-7d74-41cf-9e09-c96bd079494b.png)

**Comment by hanxiansheng26** [comment]
> 执行无输出 ![image](https://user-images.githubusercontent.com/38833353/200173783-f7ae03b4-7d74-41cf-9e09-c96bd079494b.png)

**Comment by No-Github** [comment]
<img width="502" alt="image" src="https://user-images.githubusercontent.com/18167071/201490615-8f09f3e7-0983-4adb-9685-1b338554dc7b.png">

测试了下,应该没有问题,师傅是不是 conf 文件格式错了,或者 token 不对?
